name: Run build result on server

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Run build result on server
        uses: appleboy/ssh-action@master
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.RELEASE_GOOGLE_APPLICATION_CREDENTIALS }}
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_KEY }}
          script_stop: true
          script: |
            echo "${{ secrets.RELEASE_GOOGLE_APPLICATION_CREDENTIALS }}" > /home/ubuntu/BackEnd/src/main/resources/config/secret.json
            export GOOGLE_APPLICATION_CREDENTIALS="/home/ubuntu/BackEnd/src/main/resources/config/secret.json"
            ps aux | grep BackEnd-0.0.1-SNAPSHOT.jar | grep -v grep | awk '{print $2}' | xargs kill -9
            nohup java -jar BackEnd-0.0.1-SNAPSHOT.jar &